# This file allows you to configure Airflow Connections, Pools, and Variables in a single place for local development only.
# NOTE: If putting a dict in conn_extra, please wrap in single quotes.

# For more information, refer to our docs: https://docs.astronomer.io/develop-project#configure-airflow_settingsyaml-local-development-only
# For questions, reach out to: https://support.astronomer.io
# For issues create an issue ticket here: https://github.com/astronomer/astro-cli/issues

airflow:
  connections:
    - conn_id: snowflake_default
      conn_type: snowflake
      conn_schema: <schema_name>
      conn_login: <user_login_name>
      conn_password: <password>
      conn_port:
      conn_extra: {"extra__snowflake__account": "<account_id>", 
                  "extra__snowflake__warehouse": "<warehouse_name>", 
                  "extra__snowflake__database": "<database_name>", 
                  "extra__snowflake__region": "<region_name>", 
                  "extra__snowflake__role": "<user_role_name>", 
                  "extra__snowflake__insecure_mode": false}
  pools:
    - pool_name:
      pool_slot:
      pool_description:
  variables:
    - variable_name:
      variable_value: